### PR TITLE
Switch bind and unbind in componentWillReceiveProps

### PR DESCRIPTION
**Pull request by Clement-Bresson**
I got issue : my channel and event are changing in time, and when bind method is before unbind method, subscription/unsubscription was not working correctly (there was no subscription to new channel ...)

Unbinding before binding in componentWillReceiveProps resolved this issue.

### CODE REVIEW

**Comment by oklas** [comment]
Hi! Seems your branch https://github.com/Clement-Bresson/react-pusher/commits/feature/take-update-into-account fix the problem. Thanks!

**Comment by ziahamza** [comment]
The change makes sense @Clement-Bresson! Somehow we reproduced it very late. 👍

**Comment by juliankrispel** [comment]
@ziahamza @prayogoa any chance we can get those two prs merged?

**Comment by ziahamza** [comment]
fixed by https://github.com/rainforestapp/react-pusher/pull/10

**Comment by adomrockie** [comment]
Can we merge changes?

**Comment by prayogoa** [comment]
@adomrockie this has already been fixed by #10, we just need to publish the package in npm (will do that soon)

**Pull request closed without merging**
